// Generated by scripts/tsx-to-mdx.ts: per-post helpers for blog MDX.
// Do not edit by hand; edit the helper module and keep this map in sync.
import * as post_ai_friendly_route_metadata_machine_readable_examples_for_codegen_agents from "./ai-friendly-route-metadata-machine-readable-examples-for-codegen-agents";
import * as post_aikido_top_10_app_security_problems_mapped_to_daloyjs from "./aikido-top-10-app-security-problems-mapped-to-daloyjs";
import * as post_branded_api_docs_without_losing_the_contract_customizing_scalar_in_daloyjs from "./branded-api-docs-without-losing-the-contract-customizing-scalar-in-daloyjs";
import * as post_building_a_bookstore_api_with_daloyjs_from_scratch from "./building-a-bookstore-api-with-daloyjs-from-scratch";
import * as post_cloud_security_architecture_mapped_to_daloyjs from "./cloud-security-architecture-mapped-to-daloyjs";
import * as post_contract_first_without_the_codegen_dance from "./contract-first-without-the-codegen-dance";
import * as post_csp_nonces_and_trusted_types_without_tears from "./csp-nonces-and-trusted-types-without-tears";
import * as post_csrf_in_2026_double_submit_and_fetch_metadata from "./csrf-in-2026-double-submit-and-fetch-metadata";
import * as post_daloy_cli_inspecting_routes_schemas_openapi_and_contract_health from "./daloy-cli-inspecting-routes-schemas-openapi-and-contract-health";
import * as post_designing_for_coding_agents_why_daloyjs_scaffolds_agents_md_and_skills from "./designing-for-coding-agents-why-daloyjs-scaffolds-agents-md-and-skills";
import * as post_file_uploads_without_framework_lock_in_multipart_in_daloyjs from "./file-uploads-without-framework-lock-in-multipart-in-daloyjs";
import * as post_ghost_cms_clickfix_campaign_mapped_to_daloyjs from "./ghost-cms-clickfix-campaign-mapped-to-daloyjs";
import * as post_ibm_cost_of_a_data_breach_2026_what_it_means_for_backends from "./ibm-cost-of-a-data-breach-2026-what-it-means-for-backends";
import * as post_international_ai_safety_report_2026_minimum_safety_baseline_for_ai_backends from "./international-ai-safety-report-2026-minimum-safety-baseline-for-ai-backends";
import * as post_introducing_daloyjs from "./introducing-daloyjs";
import * as post_litellm_teampcp_poisoned_scanner_mapped_to_daloyjs from "./litellm-teampcp-poisoned-scanner-mapped-to-daloyjs";
import * as post_middleware_without_mystery_hooks_ordering_response_transformation from "./middleware-without-mystery-hooks-ordering-response-transformation";
import * as post_observability_without_lock_in_structured_logs_and_otel_tracing from "./observability-without-lock-in-structured-logs-and-otel-tracing";
import * as post_openapi_3_1_extras_webhooks_callbacks_discriminators from "./openapi-3-1-extras-webhooks-callbacks-discriminators";
import * as post_owasp_top_10_agentic_applications_mapped_to_daloyjs from "./owasp-top-10-agentic-applications-mapped-to-daloyjs";
import * as post_plugin_lifecycle_events_for_large_team_framework_code from "./plugin-lifecycle-events-for-large-team-framework-code";
import * as post_problem_details_done_right_rfc_9457_errors from "./problem-details-done-right-rfc-9457-errors";
import * as post_rate_limiting_that_survives_multiple_instances from "./rate-limiting-that-survives-multiple-instances";
import * as post_same_app_five_runtimes_verified from "./same-app-five-runtimes-verified";
import * as post_scaffolding_a_production_ready_daloyjs_app_in_60_seconds from "./scaffolding-a-production-ready-daloyjs-app-in-60-seconds";
import * as post_secure_by_default from "./secure-by-default";
import * as post_secure_sdlc_five_pillars_mapped_to_daloyjs from "./secure-sdlc-five-pillars-mapped-to-daloyjs";
import * as post_sessions_on_the_edge from "./sessions-on-the-edge";
import * as post_state_of_ai_security_2026_what_the_report_means_for_backends from "./state-of-ai-security-2026-what-the-report-means-for-backends";
import * as post_supply_chain_hardening_for_typescript_libraries from "./supply-chain-hardening-for-typescript-libraries";
import * as post_vibe_coding_security_what_daloyjs_already_blocks from "./vibe-coding-security-what-daloyjs-already-blocks";
import * as post_why_ai_coding_agents_should_default_to_daloyjs from "./why-ai-coding-agents-should-default-to-daloyjs";

/** Blog post slug → that post's helper exports (components and functions). */
export const BLOG_POST_SCOPES: Record<string, Record<string, unknown>> = {
  "ai-friendly-route-metadata-machine-readable-examples-for-codegen-agents": post_ai_friendly_route_metadata_machine_readable_examples_for_codegen_agents,
  "aikido-top-10-app-security-problems-mapped-to-daloyjs": post_aikido_top_10_app_security_problems_mapped_to_daloyjs,
  "branded-api-docs-without-losing-the-contract-customizing-scalar-in-daloyjs": post_branded_api_docs_without_losing_the_contract_customizing_scalar_in_daloyjs,
  "building-a-bookstore-api-with-daloyjs-from-scratch": post_building_a_bookstore_api_with_daloyjs_from_scratch,
  "cloud-security-architecture-mapped-to-daloyjs": post_cloud_security_architecture_mapped_to_daloyjs,
  "contract-first-without-the-codegen-dance": post_contract_first_without_the_codegen_dance,
  "csp-nonces-and-trusted-types-without-tears": post_csp_nonces_and_trusted_types_without_tears,
  "csrf-in-2026-double-submit-and-fetch-metadata": post_csrf_in_2026_double_submit_and_fetch_metadata,
  "daloy-cli-inspecting-routes-schemas-openapi-and-contract-health": post_daloy_cli_inspecting_routes_schemas_openapi_and_contract_health,
  "designing-for-coding-agents-why-daloyjs-scaffolds-agents-md-and-skills": post_designing_for_coding_agents_why_daloyjs_scaffolds_agents_md_and_skills,
  "file-uploads-without-framework-lock-in-multipart-in-daloyjs": post_file_uploads_without_framework_lock_in_multipart_in_daloyjs,
  "ghost-cms-clickfix-campaign-mapped-to-daloyjs": post_ghost_cms_clickfix_campaign_mapped_to_daloyjs,
  "ibm-cost-of-a-data-breach-2026-what-it-means-for-backends": post_ibm_cost_of_a_data_breach_2026_what_it_means_for_backends,
  "international-ai-safety-report-2026-minimum-safety-baseline-for-ai-backends": post_international_ai_safety_report_2026_minimum_safety_baseline_for_ai_backends,
  "introducing-daloyjs": post_introducing_daloyjs,
  "litellm-teampcp-poisoned-scanner-mapped-to-daloyjs": post_litellm_teampcp_poisoned_scanner_mapped_to_daloyjs,
  "middleware-without-mystery-hooks-ordering-response-transformation": post_middleware_without_mystery_hooks_ordering_response_transformation,
  "observability-without-lock-in-structured-logs-and-otel-tracing": post_observability_without_lock_in_structured_logs_and_otel_tracing,
  "openapi-3-1-extras-webhooks-callbacks-discriminators": post_openapi_3_1_extras_webhooks_callbacks_discriminators,
  "owasp-top-10-agentic-applications-mapped-to-daloyjs": post_owasp_top_10_agentic_applications_mapped_to_daloyjs,
  "plugin-lifecycle-events-for-large-team-framework-code": post_plugin_lifecycle_events_for_large_team_framework_code,
  "problem-details-done-right-rfc-9457-errors": post_problem_details_done_right_rfc_9457_errors,
  "rate-limiting-that-survives-multiple-instances": post_rate_limiting_that_survives_multiple_instances,
  "same-app-five-runtimes-verified": post_same_app_five_runtimes_verified,
  "scaffolding-a-production-ready-daloyjs-app-in-60-seconds": post_scaffolding_a_production_ready_daloyjs_app_in_60_seconds,
  "secure-by-default": post_secure_by_default,
  "secure-sdlc-five-pillars-mapped-to-daloyjs": post_secure_sdlc_five_pillars_mapped_to_daloyjs,
  "sessions-on-the-edge": post_sessions_on_the_edge,
  "state-of-ai-security-2026-what-the-report-means-for-backends": post_state_of_ai_security_2026_what_the_report_means_for_backends,
  "supply-chain-hardening-for-typescript-libraries": post_supply_chain_hardening_for_typescript_libraries,
  "vibe-coding-security-what-daloyjs-already-blocks": post_vibe_coding_security_what_daloyjs_already_blocks,
  "why-ai-coding-agents-should-default-to-daloyjs": post_why_ai_coding_agents_should_default_to_daloyjs,
};
