minimumReleaseAge: 1440
blockExoticSubdeps: true
strictDepBuilds: true

overrides:
  "browserslist@<4.28.7": "4.28.9"

allowBuilds:
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
